# Generated by Django 4.1.7 on 2023-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='skill_photos/')),
            ],
            options={
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Cars'},
        ),
    ]
